url: https://aclibe.com
baseurl:

# Site settings & SEO
title: Aclibe
description: "Création, design et maintenance de site web sur Lyon. On vous propose une solution simple, efficace et de proximité."
email: aclibe.lyon@gmail.com
author: Pauline & Pierre
logo: /img/uploads/logo_120.png
google_site_verification: "Rio2fbdGxMZ-6oUwuUu4Co5F1cY54YQi4TNQ-XKSi5s"

# Collections
collections:
  - settings
  - team
  - services
  - plans
  - stories

# Postal address (add as many lines as necessary)
address:
  - line: Cordeliers
  - line: Lyon, 69002

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap