url: https://aclibe.com/
baseurl:

# Site settings
title: Aclibe
email: aclibe.lyon@gmail.com
description: "Création, design et maintenance de site web sur Lyon. On vous propose une solution simple, efficace et de proximité."

# Collections
collections:
  - settings
  - team
  - services
  - plans
  - stories

# Postal address (add as many lines as necessary)
address:
  - line: Cordeliers
  - line: Lyon, 69002

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap