backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "img/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "settings" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Settings" # Used in the UI, ie.: "New Post"
    folder: "_settings" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    delete: false # Prevent users from deleting documents in this collection
    slug: "{{slug}}"
    summary: "Settings"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "hidden", default: "settings"}
      - {label: "Display Portfolio", name: "display-portfolio", widget: "boolean"}
      - {label: "Display Clients", name: "display-clients", widget: "boolean"}
      - {label: "Header Background", name: "header-bg", widget: "image"}
      - {label: "Contact Background", name: "contact-bg", widget: "image"}

  - name: "portfolio" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Portfolio" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{order}} - {{title}} | {{subtitle}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Subtitle", name: "subtitle", widget: "string", tagname: "h3"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Order", name: "order", widget: "number", valueType: "int", default: 1}
      - {label: "Image", name: "img", widget: "image"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Alt", name: "alt", widget: "hidden", default: "image-alt"}
      - {label: "Project date", name: "project-date", widget: "datetime", format: "MMMM YYYY"}
      - {label: "Client", name: "client", widget: "hidden", default: "Start Bootstrap"}
      - {label: "Service", name: "service", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "markdown"}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}

  - name: "team" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Team Member" # Used in the UI, ie.: "New Post"
    folder: "_team" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    identifier_field: name
    summary: "{{order}} - {{name}} | {{position}}"
    fields: # The fields each document in this collection have
      - {label: "Name", name: "name", widget: "string", tagname: "h1"}
      - {label: "Position", name: "position", widget: "string", tagname: "h2"}
      - {label: "Order", name: "order", widget: "number", valueType: "int", default: 1}
      - {label: "Picture", name: "pic", widget: "image"}
      - label: "Social"
        name: "social"
        widget: "list"
        fields:
          - label: "Title"
            name: "title"
            widget: "select"
            options:
              - { label: "Google Plus", value: "google-plus" }
              - { label: "Facebook", value: "facebook" }
              - { label: "Twitter", value: "twitter" }
              - { label: "Stack Overflow", value: "stack-overflow" }
              - { label: "Pinterest", value: "pinterest" }
              - { label: "Linkedin", value: "linkedin" }
          - {label: "url", name: "url", widget: string, required: true}
      - {label: "Description", name: "body", widget: "markdown"}

  - name: "services" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Services" # Used in the UI, ie.: "New Post"
    folder: "_services" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    summary: "{{order}} - {{title}}"
    fields: # The fields each document in this collection have
      - {label: "Titre", name: "title", widget: "string", tagname: "h1"}
      - {label: "Description", name: "body", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Order", name: "order", widget: "number", valueType: "int", default: 1}

  - name: "plans" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Plans" # Used in the UI, ie.: "New Post"
    folder: "_plans" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    summary: "{{order}} - {{name}}"
    fields: # The fields each document in this collection have
      - {label: "Title (must be unique)", name: "title", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Order", name: "order", widget: "number", valueType: "int", default: 1}
      - label: "Color"
        name: "color"
        widget: "select"
        options:
          - { label: "Gray", value: "gray" }
          - { label: "Yellow", value: "yellow" }
          - { label: "Orange", value: "orange" }
      - {label: "Description", name: "body", widget: "markdown"}

  - name: "stories" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Stories" # Used in the UI, ie.: "New Post"
    folder: "_stories" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    summary: "{{order}} - {{title-date}}, {{title}}"
    fields: # The fields each document in this collection have
      - {label: "Date", name: "title-date", widget: "string", tagname: "h1"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Description", name: "body", widget: "markdown"}
      - {label: "Order", name: "order", widget: "number", valueType: "int", default: 1}
      - {label: "Image", name: "image", widget: "image"}
